name: "Terraform Plan"
description: "Validates and Tests Terraform Configuration"
inputs:
  terraform_version:
    description: "Version of Terraform to use"
    required: true
  terraform_api:
    description: "API endpoint for Terraform"
    required: true
  github_username:
    description: "GitHub username"
    required: true
  github_email:
    description: "GitHub email address"
    required: true
  github_org:
    description: "GitHub organization"
    required: true
  github_server:
    description: "GitHub server URL"
    required: false
    default: github.com
  workspace:
    description: "Workspace name"
    required: false
  varfile:
    description: "Path to the variable file"
    required: false
  autoformat_message:
    description: "Commit message for autoformatting"
    default: "AutoFormat Commit"
    required: false
  AWS_ACCESS_KEY_ID:
    description: "AWS access key ID"
    required: false
  setup_terraform:
    description: "Flag to setup Terraform"
    default: "false"
  terraform_init:
    description: "Flag to initialize Terraform"
    default: "false"
  download_cache:
    description: "Flag to download cache"
    default: "false"
  cache:
    description: "Cache configuration"
    required: false
  commit_sha:
    description: "Commit SHA"
    required: false
  uuid:
    description: "UUID"
    required: true
  cache_bucket:
    required: true
    description: "S3 Bucket to upload to"
    default: image-pipeline-assets
  cache_key:
    required: true
    description: "S3 Cache Key"
  plan_args:
    description: "Additional arguments to pass to terraform plan"
    required: false
outputs:
  commit_sha:
    description: "Commit SHA"
    value: ${{ steps.terraform.outputs.commit_sha }}
  planfile:
    description: "Name of Planfile Artifact"
    value: ${{ steps.terraform.outputs.planfile }}
  pending_changes:
    description: "Are there pending changes?"
    value: ${{ steps.terraform.outputs.pending_changes }}
  plan_succeeded:
    description: "Did the plan succeed?"
    value: ${{ steps.terraform.outputs.plan_succeeded }}

runs:
  using: "composite"
  steps:
    - uses: CSVD/gh-actions-checkout@v4
      id: checkout
      with:
        ref: ${{ inputs.commit_sha == '' && github.head_ref || inputs.commit_sha }}
        persist-credentials: false

    - name: Download Terraform Directory
      uses: CSVD/s3-download@main
      if: ${{ inputs.download_cache == 'true' }}
      with:
        bucket: ${{ inputs.cache_bucket }}
        cache_key: ${{ inputs.cache_key }}/terraform-dir
        dest: .
        unarchive: true

    - name: Download Terraform Lockfile
      uses: CSVD/s3-download@main
      if: ${{ inputs.download_cache == 'true' }}
      with:
        bucket: ${{ inputs.cache_bucket }}
        cache_key: ${{ inputs.cache_key }}/terraform.lock.hcl
        dest: .terraform.lock.hcl
        unarchive: false

    - name: fix file permissions
      if: ${{ inputs.download_cache == 'true' }}
      run: chmod -R 600 .terraform.lock.hcl
      shell: bash
      
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 16

    - name: Setup Terraform
      uses: CSVD/gh-actions-setup-terraform@v2
      if: ${{ inputs.setup_terraform && env.TFE_TOKEN != '' }}
      with:
        terraform_version: ${{ inputs.terraform_version }}
        cli_config_credentials_token: ${{ env.TFE_TOKEN }}
        cli_config_credentials_hostname: ${{ inputs.terraform_api }}

    - name: Setup Terraform
      uses: CSVD/gh-actions-setup-terraform@v2
      if: ${{ inputs.setup_terraform && env.TFE_TOKEN == '' }}
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Set Workspace
      shell: bash
      if: ${{ inputs.workspace != '' }}
      run: |
        echo "TF_WORKSPACE=${{ inputs.workspace }}" >> $GITHUB_ENV

    - name: Set TF_CLI_ARGS (Varfile)
      shell: bash
      if: ${{ inputs.varfile != '' }}
      run: |
        echo "TF_CLI_ARGS=-var-file=${{ inputs.varfile }} ${{ inputs.plan_args }}" >> $GITHUB_ENV

    - name: Set TF_CLI_ARGS (NonVarfile)
      shell: bash
      if: ${{ inputs.varfile == '' }}
      run: |
        echo "TF_CLI_ARGS='${{ inputs.plan_args }}" >> $GITHUB_ENV
    
    - name: Terraform Init
      id: init
      shell: bash
      if: ${{ inputs.terraform_init == 'true' }}
      run: terraform init -upgrade
     
    - name: Terraform Plan
      id: plan
      continue-on-error: true
      shell: bash
      run: |
        terraform plan -detailed-exitcode -out=tf.plan
        exit_code=$?
        if [ $exit_code -eq 2 ]; then
          echo plan_succeeded=true >> $GITHUB_OUTPUT
          echo pending_changes=true >> $GITHUB_OUTPUT
        elif [ $exit_code -eq 0 ]; then
          echo plan_succeeded=true >> $GITHUB_OUTPUT
          echo pending_changes=false >> $GITHUB_OUTPUT
        else
          echo plan_succeeded=false >> $GITHUB_OUTPUT
          echo pending_changes=false >> $GITHUB_OUTPUT
        fi

    - uses: CSVD/s3-upload@main
      name: Archive Planfile
      with:
        source: tf.plan
        bucket: ${{ inputs.cache_bucket }}
        archive: false
        key: ${{ inputs.cache_key }}/terraform.plan
     
    - name: Unset TF_CLI_ARGS
      shell: bash
      run: |
        echo "TF_CLI_ARGS=''" >> $GITHUB_ENV
        
    - name: Terraform Plan
      id: plan_output
      shell: bash
      run: |
        echo "tf_plan=$(/opt/tfenv/bin/terraform show -no-color tf.plan)" >> $GITHUB_ENV
        
    - uses: CSVD/gh-actions-github-script@v7
      env:
        PLAN: "${{ env.tf_plan }}"
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        script: |
          // 1. Retrieve existing bot comments for the PR
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const botComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('Terraform Plan')
          })

          // 2. Prepare format of the comment
          const output = #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

          // 3. If we have a comment, update it, otherwise create a new one
          if (botComment) {
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: output
            })
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
          }
